### PR TITLE
Update BARMM regions and other missing data

### PR DESCRIPTION
**Pull request by galoberlyn**
- The Autonomous Region in Muslim Mindanao (ARMM) in the Philippines was replaced by the Bangsamoro Autonomous Region in Muslim Mindanao (BARMM) through the passage of the Bangsamoro Organic Law (Republic Act No. 11054) in 2018. The BARMM was established to provide greater autonomy and self-governance to the Muslim-majority areas in Mindanao, replacing the ARMM.

- Added additional data

### CODE REVIEW

**Review by pcofilada — CHANGES_REQUESTED** [review]
@galoberlyn thank you for the pull request. Just one thing can you fix the indentation to use two spaces only just to make it consistent with the others. Thank you!

**Comment by galoberlyn** [comment]
Prettified by https://jsonformatter.org/json-pretty-print thanks!

**Review by pcofilada — APPROVED** [review]
Looks good to me. 👍

**Comment by pcofilada** [comment]
I'll be merging this one and releasing a new version. Thank you @galoberlyn

**Pull request merged**
